language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"

before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
deploy:
  provider: heroku
  api_key: heroku_api_key
  app: trustworthywonton

